---
title: "Data_cleaning"
format: html
---

```{r}
library(here)
library(tidyverse)
library(ggplot2)
library(readr)
library(rstatix)
library(janitor)
library(dplyr)
library(knitr)
library(haven)
library(gt)
```


###Load data

```{r}
NHANES_Demo_1718 <- read_xpt("Data/DEMO_J.xpt")
NHANES_Demo_1516 <- read_xpt("Data/DEMO_I.xpt")
NHANES_Demo_1314 <- read_xpt("Data/DEMO_H.xpt")
```

```{r}
NHANES_BMI_1718 <- read_xpt("Data/BMX_J.xpt")
NHANES_BMI_1516 <- read_xpt("Data/BMX_I.xpt")
NHANES_BMI_1314 <- read_xpt("Data/BMX_H.xpt")
```

###DM(Diabetes Melliitus)

```{r}
NHANES_DM_1718 <- read_xpt("Data/DIQ_J.xpt")
NHANES_DM_1516 <- read_xpt("Data/DIQ_I.xpt")
NHANES_DM_1314 <- read_xpt("Data/DIQ_H.xpt")
```

## HINSUR
```{r}
NHANES_Hinsur_1718 <- read_xpt("Data/HIQ_J.xpt")
NHANES_Hinsur_1516 <- read_xpt("Data/HIQ_I.xpt")
NHANES_Hinsur_1314 <- read_xpt("Data/HIQ_H.xpt")
```

## (Medcon)
```{R}
NHANES_MC_1718 <- read_xpt("Data/MCQ_J.xpt")
NHANES_MC_1516 <- read_xpt("Data/MCQ_I.xpt")
NHANES_MC_1314 <- read_xpt("Data/MCQ_H.xpt")
```

## Physical Activty

```{r}
NHANES_PA_1718 <- read_xpt("Data/PAQ_J.xpt")
NHANES_PA_1516 <- read_xpt("Data/PAQ_I.xpt")
NHANES_PA_1314 <- read_xpt("Data/PAQ_H.xpt")
```

#Smoking
```{R}
NHANES_SMK_1718 <- read_xpt("Data/SMQ_J.xpt")
NHANES_SMK_1516 <- read_xpt("Data/SMQ_I.xpt")
NHANES_SMK_1314 <- read_xpt("Data/SMQ_H.xpt")
```

```{R}
NHANES_demo_merged <- bind_rows(NHANES_Demo_1314, 
                         NHANES_Demo_1516, 
                         NHANES_Demo_1718)
```

```{r}
NHANES_BMI_merged <- bind_rows(NHANES_BMI_1314, 
                         NHANES_BMI_1516, 
                         NHANES_BMI_1718)
```


```{r}
NHANES_DM_merged <- bind_rows(NHANES_DM_1314, 
                         NHANES_DM_1516, 
                         NHANES_DM_1718)
```

```{r}
NHANES_Hinsur_merged <- bind_rows(NHANES_Hinsur_1314, 
                         NHANES_Hinsur_1516, 
                         NHANES_Hinsur_1718)
```

```{R}
NHANES_MC_merged <- bind_rows(NHANES_MC_1314, 
                         NHANES_MC_1516, 
                         NHANES_MC_1718)
```

```{r}
NHANES_PA_merged <- bind_rows(NHANES_PA_1314, 
                         NHANES_PA_1516, 
                         NHANES_PA_1718)
```

```{r}
NHANES_SMK_merged <- bind_rows(NHANES_SMK_1314, 
                         NHANES_SMK_1516, 
                         NHANES_SMK_1718)
```


## Create analytic sample

```{R}
BMI_vars <- NHANES_BMI_merged %>% select( SEQN, BMXBMI)
SMK_vars <- NHANES_SMK_merged %>% select(SEQN, SMQ020, SMQ621)
DM_vars <- NHANES_DM_merged %>% select(SEQN, DIQ010)
Hinsur_vars <- NHANES_Hinsur_merged %>% select(SEQN , HIQ011)
MC_vars <- NHANES_MC_merged %>% select(SEQN, MCQ160A, MCQ195)
PA_vars <- NHANES_PA_merged %>% select(SEQN, PAQ605, PAQ610, PAQ620, PAD615, PAQ625, PAD630)
```


#MET Score coding

```{R}
PA_vars$MET_vig <- PA_vars$PAD615*8
PA_vars$MET_mod <- PA_vars$PAD630 * 4
PA_vars$MET_total <- PA_vars$MET_vig + PA_vars$MET_mod
```

#BMI catagorical

Underweight/Normal = 0
Overweight = 1
Obese = 2

```{R}
NHANES_analytic <- NHANES_analytic %>%
  mutate(BMI_cat = case_when(
    BMXBMI < 25 ~ "Underweight/Normal",
    BMXBMI >= 25 & BMXBMI <= 30 ~ "Overweight",
    BMXBMI > 30 ~ "Obese",
  ))
```

```{R}
table(NHANES_analytic$BMI_cat) 
```


```{r}
NHANES_analytic <- NHANES_demo_merged %>%
  left_join(BMI_vars,   by = "SEQN") %>%
  left_join(SMK_vars,   by = "SEQN") %>%
  left_join(DM_vars,    by = "SEQN") %>%
  left_join(Hinsur_vars, by = "SEQN") %>%
  left_join(MC_vars,    by = "SEQN") %>%
  left_join(PA_vars,    by = "SEQN")

NHANES_analytic %>%
  clean_names()
```

#Total: 29400 Participants of 64 variables


```{R}
# of cases age 
NHANES_analytic %>%
  filter(RIDAGEYR >= 20 & RIDAGEYR <= 65) %>%
  nrow()

NHANES_analytic
```
20-65 yo : 13141


#Mutate / Recode

Arthritis: MCQ 160a : 1 = Yes, 2= No , Other = 0


```{r}
NHANES_analytic <- NHANES_analytic %>%
  mutate(
    Arthritis = case_when(
      MCQ160A == 1 ~ 1,
      MCQ160A == 2 ~ 0,
      MCQ160A == 9 ~ 0,
      is.na(MCQ160A) ~ 0
    ),
    Osteo_yn = if_else(MCQ195 == 1, 1, 0, missing = 0),
    age_cat = case_when(
      RIDAGEYR >= 20 & RIDAGEYR <= 29 ~ "20-29",
      RIDAGEYR >= 30 & RIDAGEYR <= 44 ~ "30-44",
      RIDAGEYR >= 45 & RIDAGEYR <= 64 ~ "45-64",
      RIDAGEYR >= 65 ~ "65+"
    ),
    Hinsur_yn = case_when(
      HIQ011 == 1 ~ "Yes",
      HIQ011 == 2 ~ "No"
    ),
    smk_status = case_when(
      SMQ020 == 1 ~ "Yes"
      SMQ020 == 2 ~ "No"
    ),
     RE_cat = case_when(
       RIDRETH3 == 1 ~ "Mexican American",
       RIDRETH3 == 3 ~ "White",
       RIDRETH3 == 4 ~ "Black",
       RIDRETH3 == 6 ~ "Asian",
       RIDRETH3 == 2 & RIDRETH3 == 7 ~ "Mixed/Other"
     ),
    
    )
```

#Arthritis type

Osteo = 1
All other = 0


```{R}
NHANES_analytic %>%
  filter(Osteo_yn == 1) %>%
  nrow()
```
Total yes osteo 2021

```{r}
table(NHANES_analytic$Osteo_yn)
```

